redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  service:
    type: LoadBalancer
    loadBalancerClass: service.k8s.aws/nlb
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
repoServer:
  replicas: 1

applicationSet:
  replicas: 1

#global:
#  domain: localhost

certificate:
  enabled: true

#server:
#  ingress:
#    enabled: true
#    ingressClassName: "alb"
##    ingressClassName: "traefik"
#    tls: true