image:
  repository: johnyunez/python-api-app
  pullPolicy: IfNotPresent
  tag: '251021-1648'
replicaCount: 2
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
service:
  type: LoadBalancer
  port: 5000
ingress:
  enabled: false
  ClassName: "alb"
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /api
          pathType: Prefix
  tls: []
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
