apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.service.annotations.aws-load-balancer-scheme }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "python-app.selectorLabels" . | nindent 4 }}
