name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag for dockerhub version
        shell: bash
        run: |
          echo "IMAGE_VERSION=$(date +'%y%m%d-%H%M')" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: johnyunez/python-api-app:${{ env.IMAGE_VERSION }}
jobs:
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      -
        name: Argocd login
        uses: imranismail/setup-argocd@v2
        with:
          argocd_server: argocd-server.argocd
          argocd_username: ${{ vars.ARGOCD_USERNAME }}
          argocd_password: ${{ secrets.ARGOCD_PASSWORD }}
      -
        name: Argocd app sync
        shell: bash
        run: |
          # argocd login argocd-server.argocd \
            --insecure \
            --username ${{ vars.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app --hard-refresh
