name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set tag for dockerhub version
        shell: bash
        run: |
          echo "IMAGE_VERSION=$(date +'%y%m%d-%H%M')" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: johnyunez/python-api-app:${{ env.IMAGE_VERSION }}
    outputs:
      image_version: ${{ env.IMAGE_VERSION }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Update charts/values/image.tag tag with new dockerhub image
        shell: bash
        run: |
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.image_version }}"' ./charts/python-app/values.yaml
      -
        name: Commit changes to charts/values/image.tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "github-actions.cd: update image tag to ${{ needs.ci.outputs.image_version }}"
          branch: master
          file_pattern: "charts/python-app/values.yaml"
      -
        name: Install Argocd
        shell: bash
        run: |
          sudo curl -sSLk -o /usr/local/bin/argocd https://argocd-server.argocd/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd 
      -
        name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --username ${{ vars.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-api-app
